### ISSUE TITLE
[Bug] Level-5 bcrypt hashing error

### ISSUE THREAD

**Issue by junque1r4** [skills/secure-code-game#18]
**Describe the bug**
SHA256_hasher.password_hash fails the tests because Random_generator.generate_salt() aren't generating valid salts to the bcrypt.hashpw

**To Reproduce**
1. Run `python3 tests.py`

**Expected behavior**
The tests should pass.

**Screenshots**
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/39351332/230209203-d7eb7cea-f7d8-48ab-b01f-e7d24f4cec21.png">

**Device information**
 - Type: MacBook
 - OS: Ventura 13.2.1 (22D68)
 - Python: 3.9.6 
- Clang: 14.0.0 (clang-1400.0.29.202)

**Additional context**
Analyzing how  bcrypt.gensalt() generates  base64 encoding I see that it doesn't match any other base64 encodings: 
<img width="254" alt="image" src="https://user-images.githubusercontent.com/39351332/230209757-10cde190-8bff-4a18-958a-2c0e3b5310a3.png">
<img width="381" alt="image" src="https://user-images.githubusercontent.com/39351332/230209998-d581afeb-da7e-4c7c-af68-aff9381cfe63.png">
So, even generating valid base64 bytes the hashpw aren't working

**Comment by jkcso** [comment]
Thank you! We are working on it and feel free to submit a PR if you so want to!

**Comment by junque1r4** [comment]
I have performed additional tests and discovered that the issue is not related to how we implemented our Base64 encoding, but rather to the Bcrypt library itself. I was wondering if it would be possible to use another library for this exercise, or if Bcrypt is really needed for the exercise purposes.

**Comment by jkcso** [comment]
@junque1r4 You can use any library you want. We tried to emphasise this in our solution too by mentioning the characteristics that a suitable/safe library should have.

Please use another library and let me know if you want to propose a second `solution.py` file that uses another library, by opening a PR.

**Comment by junque1r4** [comment]
@jkcso Pull Request Opened. The exercise is the same but now in Kotlin!
I wanted to diversify the challenge to Kotlin since it's a more modern language and closer to Java. I hope it's a valid addition.

**Comment by jkcso** [comment]
A big thank you for your valuable contribution! We will review and decide if we can add it!

**Comment by Cito** [comment]
When base64 decoding 22 random digits, the result can sometimes have more than 16 bytes, which will generate the 
"invalid salt" error.

This could be solved by base64 encoding 16 random digits. But as already noticed above, bcrypt does not use the standard base64 table. Not only does it use different altchars, its also puts them at the beginning instead of at the end. Unfortunately, the base64 module of Python does only allow changing the altchars, not the complete table.

However, we just want to provide a random salt that is not longer than 16 bytes when base64 decoded. This can be done by adding a `.` at the end which base64 decodes to zeroes (using the bcrypt table for base64).

So, my suggestion is to use the following code as vulnerable example:

```python
def generate_salt(self, rounds=12):
    salt = ''.join(str(random.randint(0,9)) for _ in range(21)) + '.'
    return f'$2b${rounds}${salt}'.encode()
```
   
This shows the same flaws as the original code:
- reinvents the wheel (generates salt manually instead of calling `gensalt()`)
- does not utilize the full range of possible salt values
- uses the `random` module instead of the `secrets` module

**Comment by jkcso** [comment]
@Cito love it, feel free to open a PR closing this issue!
